use casper_types::ApiError;

#[repr(u16)]
pub enum Errors {
    TransferHelperWrongSender = 5,
    NotActive,
    InvalidValue1,
    InvalidHash1,
    InvalidHash2,
    InvalidHash3,
    InvalidHash4,
    InvalidHash5,
    InvalidHash6,
    InvalidHash7,
    InvalidHash8,
    InvalidHash9,
    TransferFailed,
    TransferFromFailed,
    SnapshotDayDoesNotExistYet,
    SnapshotAlreadyTakenForThatDay,
    AdditionOverflow1,
    AdditionOverflow2,
    AdditionOverflow3,
    AdditionOverflow4,
    AdditionOverflow5,
    AdditionOverflow6,
    AdditionOverflow7,
    AdditionOverflow8,
    AdditionOverflow9,
    AdditionOverflow10,
    AdditionOverflow11,
    AdditionOverflow12,
    // SubtractionUnderflow1,
    // SubtractionUnderflow2,
    // SubtractionUnderflow3,
    // SubtractionUnderflow4,
    // SubtractionUnderflow5,
    // SubtractionUnderflow6,
    // SubtractionUnderflow7,
    // SubtractionUnderflow8,
    // SubtractionUnderflow9,
    // SubtractionUnderflow10,
    // SubtractionUnderflow11,
    // SubtractionUnderflow12,
    SubtractionUnderflow13,
    SubtractionUnderflow14,
    SubtractionUnderflow15,
    SubtractionUnderflow16,
    // SubtractionUnderflow17,
    // SubtractionUnderflow18,
    // SubtractionUnderflow19,
    MultiplicationOverflow1,
    MultiplicationOverflow2,
    MultiplicationOverflow3,
    MultiplicationOverflow4,
    DivisionByZero1,
    DivisionByZero2,
    DivisionByZero3,
    DivisionByZero4,
}

impl From<Errors> for ApiError {
    fn from(error: Errors) -> ApiError {
        ApiError::User(error as u16)
    }
}
